In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
dataset = pd.read_csv(r'd:\00 - Woxsen\MBA (Business Analytics)\Term 3 - Subjects\Machine Learning for Business\11Mar25\50_startups.csv')

In [3]:
dataset

R&D Spend  Administration  Marketing Spend        City     Profit
0   165349.20       136897.80        471784.10     Chennai  192261.83
1   162597.70       151377.59        443898.53     Madurai  191792.06
2   153441.51       101145.55        407934.54  Coimbatore  191050.39
3   144372.41       118671.85        383199.62     Chennai  182901.99
4   142107.34        91391.77        366168.42  Coimbatore  166187.94
5   131876.90        99814.71        362861.36     Chennai  156991.12
6   134615.46       147198.87        127716.82     Madurai  156122.51
7   130298.13       145530.06        323876.68  Coimbatore  155752.60
8   120542.52       148718.95        311613.29     Chennai  152211.77
9   123334.88       108679.17        304981.62     Madurai  149759.96
10  101913.08       110594.11        229160.95  Coimbatore  146121.95
11  100671.96        91790.61        249744.55     Madurai  144259.40
12   93863.75       127320.38        249839.44  Coimbatore  141585.52
13   91992.39       135495.07        252664.93     Madurai  134307.35
14  119943.24       156547.42        256512.92  Coimbatore  132602.65
15  114523.61       122616.84        261776.23     Chennai  129917.04
16   78013.11       121597.55        264346.06     Madurai  126992.93
17   94657.16       145077.58        282574.31     Chennai  125370.37
18   91749.16       114175.79        294919.57  Coimbatore  124266.90
19   86419.70       153514.11             0.00     Chennai  122776.86
20   76253.86       113867.30        298664.47     Madurai  118474.03
21   78389.47       153773.43        299737.29     Chennai  111313.02
22   73994.56       122782.75        303319.26  Coimbatore  110352.25
23   67532.53       105751.03        304768.73  Coimbatore  108733.99
24   77044.01        99281.34        140574.81     Chennai  108552.04
25   64664.71       139553.16        137962.62     Madurai  107404.34
26   75328.87       144135.98        134050.07  Coimbatore  105733.54
27   72107.60       127864.55        353183.81     Chennai  105008.31
28   66051.52       182645.56        118148.20  Coimbatore  103282.38
29   65605.48       153032.06        107138.38     Chennai  101004.64
30   61994.48       115641.28         91131.24  Coimbatore   99937.59
31   61136.38       152701.92         88218.23     Chennai   97483.56
32   63408.86       129219.61         46085.25     Madurai   97427.84
33   55493.95       103057.49        214634.81  Coimbatore   96778.92
34   46426.07       157693.92        210797.67     Madurai   96712.80
35   46014.02        85047.44        205517.64     Chennai   96479.51
36   28663.76       127056.21        201126.82  Coimbatore   90708.19
37   44069.95        51283.14        197029.42     Madurai   89949.14
38   20229.59        65947.93        185265.10     Chennai   81229.06
39   38558.51        82982.09        174999.30     Madurai   81005.76
40   28754.33       118546.05        172795.67     Madurai   78239.91
41   27892.92        84710.77        164470.71  Coimbatore   77798.83
42   23640.93        96189.63        148001.11     Madurai   71498.49
43   15505.73       127382.30         35534.17     Chennai   69758.98
44   22177.74       154806.14         28334.72     Madurai   65200.33
45    1000.23       124153.04          1903.93     Chennai   64926.08
46    1315.46       115816.21        297114.46  Coimbatore   49490.75
47       0.00       135426.92             0.00     Madurai   42559.73
48     542.05        51743.15             0.00     Chennai   35673.41
49       0.00       116983.80         45173.06     Madurai   14681.40

In [4]:
dataset.isnull().sum()

R&D Spend          0
Administration     0
Marketing Spend    0
City               0
Profit             0
dtype: int64

In [5]:
# dependent and independent variables
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, 4].values

In [8]:
# convert categorial to numerical
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.compose import ColumnTransformer
le_x = LabelEncoder()
x[:, 3] = le_x.fit_transform(x[:, 3])
ohe_x = ColumnTransformer(
    [('one_hot_encoder', OneHotEncoder(), [3])],
    remainder = 'passthrough'
)
x = np.array(ohe_x.fit_transform(x), dtype = int)

In [9]:
x

array([[     1,      0,      0, 165349, 136897, 471784],
       [     0,      0,      1, 162597, 151377, 443898],
       [     0,      1,      0, 153441, 101145, 407934],
       [     1,      0,      0, 144372, 118671, 383199],
       [     0,      1,      0, 142107,  91391, 366168],
       [     1,      0,      0, 131876,  99814, 362861],
       [     0,      0,      1, 134615, 147198, 127716],
       [     0,      1,      0, 130298, 145530, 323876],
       [     1,      0,      0, 120542, 148718, 311613],
       [     0,      0,      1, 123334, 108679, 304981],
       [     0,      1,      0, 101913, 110594, 229160],
       [     0,      0,      1, 100671,  91790, 249744],
       [     0,      1,      0,  93863, 127320, 249839],
       [     0,      0,      1,  91992, 135495, 252664],
       [     0,      1,      0, 119943, 156547, 256512],
       [     1,      0,      0, 114523, 122616, 261776],
       [     0,      0,      1,  78013, 121597, 264346],
       [     1,      0,      0,

In [12]:
# split and train data
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.30, random_state = 0)

In [13]:
# MLR model from sklearn
from sklearn.linear_model import LinearRegression
regress = LinearRegression()
regress.fit(x_train, y_train)

LinearRegression()

In [14]:
# prediction
y_pred = regress.predict(x_test)

In [15]:
y_pred

array([104282.74845357, 132536.53849928, 133911.11921422,  72584.3557291 ,
       179920.88369286, 114549.21392778,  66444.25735029,  98404.98885339,
       114499.77312619, 169367.57489704,  96522.21039594,  88040.95894935,
       110949.65365897,  90419.61586831, 128020.69204362])

In [16]:
y_test

array([103282.38, 144259.4 , 146121.95,  77798.83, 191050.39, 105008.31,
        81229.06,  97483.56, 110352.25, 166187.94,  96778.92,  96479.51,
       105733.54,  96712.8 , 124266.9 ])

In [17]:
# model performance - Best fitted line error rate
regress.score(x_train, y_train)

0.9515563254725671

In [18]:
regress.score(x_test, y_test)

0.9358682078683129

In [19]:
# Lets build the model using backward elimination
# Now we will use linear regression from statemodel library
import statsmodels.api as sm

In [20]:
x = np.append(arr = np.ones(shape=(50, 1), dtype = int), values = x, axis = 1) # x = c+x
# x = np.append(arr = x, values = np.ones(shape=(50, 1), dtype = int), axis = 1) # x = x+c

In [21]:
x

array([[     1,      1,      0,      0, 165349, 136897, 471784],
       [     1,      0,      0,      1, 162597, 151377, 443898],
       [     1,      0,      1,      0, 153441, 101145, 407934],
       [     1,      1,      0,      0, 144372, 118671, 383199],
       [     1,      0,      1,      0, 142107,  91391, 366168],
       [     1,      1,      0,      0, 131876,  99814, 362861],
       [     1,      0,      0,      1, 134615, 147198, 127716],
       [     1,      0,      1,      0, 130298, 145530, 323876],
       [     1,      1,      0,      0, 120542, 148718, 311613],
       [     1,      0,      0,      1, 123334, 108679, 304981],
       [     1,      0,      1,      0, 101913, 110594, 229160],
       [     1,      0,      0,      1, 100671,  91790, 249744],
       [     1,      0,      1,      0,  93863, 127320, 249839],
       [     1,      0,      0,      1,  91992, 135495, 252664],
       [     1,      0,      1,      0, 119943, 156547, 256512],
       [     1,      1,  

In [23]:
# Backward elimination
x_ov = x[:, [0, 1, 2, 3, 4, 5]] # x_ov = x
regress_ols = sm.OLS(endog = y, exog = x_ov).fit()
regress_ols.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.948
Model:                            OLS   Adj. R-squared:                  0.943
Method:                 Least Squares   F-statistic:                     205.0
Date:                Tue, 11 Mar 2025   Prob (F-statistic):           2.90e-28
Time:                        11:37:32   Log-Likelihood:                -526.75
No. Observations:                  50   AIC:                             1064.
Df Residuals:                      45   BIC:                             1073.
Df Model:                           4                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       4.122e+04   4607.954      8.945      0.000    3.19e+04    5.05e+04
x1          1.335e+04   2459.316      5.428      0.000    8395.644    1.83e+04
x2          1.448e+04   2518.999      5.748      0.000    9405.977    1.96e+04
x3          1.339e+04   2421.512      5.529      0.000    8511.254    1.83e+04
x4             0.8609      0.031     27.665      0.000       0.798       0.924
x5            -0.0527      0.050     -1.045      0.301      -0.154       0.049
==============================================================================
Omnibus:                       14.276   Durbin-Watson:                   1.197
Prob(Omnibus):                  0.001   Jarque-Bera (JB):               19.262
Skew:                          -0.953   Prob(JB):                     6.57e-05
Kurtosis:                       5.369   Cond. No.                     7.98e+17
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 1.69e-24. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.
"""

In [24]:
x_ov

array([[     1,      1,      0,      0, 165349, 136897],
       [     1,      0,      0,      1, 162597, 151377],
       [     1,      0,      1,      0, 153441, 101145],
       [     1,      1,      0,      0, 144372, 118671],
       [     1,      0,      1,      0, 142107,  91391],
       [     1,      1,      0,      0, 131876,  99814],
       [     1,      0,      0,      1, 134615, 147198],
       [     1,      0,      1,      0, 130298, 145530],
       [     1,      1,      0,      0, 120542, 148718],
       [     1,      0,      0,      1, 123334, 108679],
       [     1,      0,      1,      0, 101913, 110594],
       [     1,      0,      0,      1, 100671,  91790],
       [     1,      0,      1,      0,  93863, 127320],
       [     1,      0,      0,      1,  91992, 135495],
       [     1,      0,      1,      0, 119943, 156547],
       [     1,      1,      0,      0, 114523, 122616],
       [     1,      0,      0,      1,  78013, 121597],
       [     1,      1,      0,

In [25]:
x_ovc = x_ov[:, 1:]

In [26]:
# split and train data
from sklearn.model_selection import train_test_split
x_ov_train, x_ov_test, y_ov_train, y_ov_test = train_test_split(x_ovc, y, test_size = 0.30, random_state = 0)

# MLR model from sklearn
from sklearn.linear_model import LinearRegression
regress_ov1 = LinearRegression()
regress_ov1.fit(x_ov_train, y_ov_train)

LinearRegression()

In [27]:
regress_ov1.score(x_ov_train, y_ov_train)

0.9481089427146575

In [28]:
regress_ov1.score(x_ov_test, y_ov_test)

0.9358389432206486